create table if not exists public.visites (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  page text not null,
  user_agent text
);

alter table public.visites enable row level security;

create policy "Autoriser l'ajout de visites"
on public.visites
for insert
to anon
with check (true);

create policy "Autoriser la lecture des visites"
on public.visites
for select
to anon
using (true);
